### ISSUE TITLE
version 0.2.1 generates error in jupyter lab and Internal Server Error on Jupyter notebook

### ISSUE THREAD

**Issue by andibuwono** [timkpaine/jupyterlab_commands#22]
Hi. I'm recently upgrade to 0.2.1 from 0.2.0.

which caused the jupyter lab error  'ModuleNotFoundError: No module named 'jupyterlab_commands.nbconvert_functions'  in the console, and if i use the notebook mode internal server error occured.

Everything are fine if I rollback to 0.2.0

here are captures:

`   HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1589471135971', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\development\python\python37\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\development\python\python37\lib\site-packages\tornado\web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "c:\development\python\python37\lib\site-packages\notebook\services\nbconvert\handlers.py", line 21, in get
        exporter_class = base.get_exporter(exporter_name)
      File "c:\development\python\python37\lib\site-packages\nbconvert\exporters\base.py", line 98, in get_exporter
        return entrypoints.get_single('nbconvert.exporters', name).load()
      File "c:\development\python\python37\lib\site-packages\entrypoints.py", line 82, in load
        mod = import_module(self.module_name)
      File "c:\development\python\python37\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab_commands.nbconvert_functions'`

`PS C:\Users\andib> jupyter labextension list
JupyterLab v2.1.2
Known labextensions:
   app dir: c:\development\python\python37\share\jupyter\lab
        @bokeh/jupyter_bokeh v2.0.1 enabled  ok
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        @jupyterlab/debugger v0.2.0 enabled  ok
        @jupyterlab/shortcutui v0.5.0-beta.2 enabled  ok
        @jupyterlab/toc v3.0.0 enabled  ok
        @krassowski/jupyterlab-lsp v1.0.0 disabled ok
        @lckr/jupyterlab_variableinspector v0.5.0 enabled  ok
        @wallneradam/trailing_space_remover v0.5.0 enabled  ok*
        bqplot v0.5.10 enabled  ok
        ipyevents v1.7.1 enabled  ok
        jupyter-leaflet v0.12.6 enabled  ok
        jupyter-matplotlib v0.7.2 enabled  ok
        jupyter-threejs v2.2.0 enabled  ok
        jupyterlab-flake8 v0.6.1 enabled  ok
        jupyterlab-jupytext v1.2.1 enabled  ok
        jupyterlab-python-file v0.4.0 enabled  ok
        jupyterlab_commands v0.2.1 enabled  ok
        qgrid2 v1.1.3 enabled  ok`

**Comment by timkpaine** [comment]
looks like I forgot remove the entry points, I'll release a 0.2.2 soon

**Comment by timkpaine** [comment]
@andibuwono can you test 0.2.2

**Comment by andibuwono** [comment]
Hi sorry for late response, I tested and the problem was gone
